-- 2022년 1월의 도서 판매 데이터를 기준으로
-- 저자별, 카테고리별 매출액(TOTAL_SALES = 판매량 * 판매가) 구하여
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카데고리(CATEGORY), 매출액(SALES)
-- 저자 ID ASC, 카테고리 DESC
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((BS.SALES * B.PRICE)) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
    ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN BOOK_SALES BS
    ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE LIKE "2022-01%"
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;
