-- root 아이템을 찾아 작성(ITEM_ID, ITEM_NAME)
-- 아이템 ID 기준으로 오름차순 정렬
SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I, ITEM_TREE T
WHERE 1=1
    AND I.ITEM_ID = T.ITEM_ID
    AND PARENT_ITEM_ID IS NULL
ORDER BY I.ITEM_ID;