-- 3세대의 대장균의 ID
-- 대장균의 ID에 대한 오름차순 정렬
-- 최초의 대장균 개체의 PARENT_ID == NULL
SELECT E1.ID
FROM ECOLI_DATA E1
JOIN ECOLI_DATA E2
ON E1.PARENT_ID = E2.ID
JOIN ECOLI_DATA E3
ON E2.PARENT_ID = E3.ID
WHERE E2.PARENT_ID IS NOT NULL AND E3.PARENT_ID IS NULL
ORDER BY ID ASC;