SELECT ED.ID,
    CASE
        WHEN ED.PER <= 0.25 THEN "CRITICAL"
        WHEN ED.PER <= 0.5 THEN "HIGH"
        WHEN ED.PER <= 0.75 THEN "MEDIUM"
        ELSE "LOW"
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK()
                OVER(ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA
) AS ED
ORDER BY ED.ID ASC;