SELECT U.USER_ID,
    NICKNAME, 
    CONCAT(CITY, " ", STREET_ADDRESS1, " ",STREET_ADDRESS2) 전체주소, 
    CONCAT(LEFT(TLNO,3),'-',MID(TLNO, 4, 4),'-',RIGHT(TLNO,4)) 전화번호
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B
ON U.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(*) >=3
ORDER BY U.USER_ID DESC;