-- 각 분기(QUARTER)별 대장균의 개체의 총 수(ECOLI_COUNT)
-- 분기에는 'Q'를 붙이기
-- 1~3 / 4~6 / 7~9 / 10~12
-- 분기 기준 오름차순
WITH QUARTER_TABLE AS (
    SELECT 
    CASE
        WHEN RIGHT(DIFFERENTIATION_DATE, 5) <= "03-31" THEN 1
        WHEN RIGHT(DIFFERENTIATION_DATE, 5) <= "06-30" THEN 2
        WHEN RIGHT(DIFFERENTIATION_DATE, 5) <= "09-30" THEN 3
        WHEN RIGHT(DIFFERENTIATION_DATE, 5) <= "12-31" THEN 4
    END AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM
        ECOLI_DATA
GROUP BY
        QUARTER
)
SELECT
    CONCAT(QUARTER, "Q") AS QUARTER,
    ECOLI_COUNT
FROM
        QUARTER_TABLE
ORDER BY
        QUARTER;