-- 7월의 아이스크림 총 주문량
-- 주문량 순서대로 상위 3개의 맛만 조회
SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN JULY J
ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY (SUM(FH.TOTAL_ORDER) + SUM(J.TOTAL_ORDER)) DESC
LIMIT 3;