-- 완료된 중고 거래의 총금액이 70만원 이상인 사람의 회원 ID, 닉네임, 총 거래 금액
-- 총 거래 금액 기준 오름차순
SELECT U.USER_ID, U.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;