-- 부모의 형질을 모두 보유한 대장균의 IDx, GENOTYPE, PARENT_GENOTYHPE 출력
-- id 오름차순
-- 부모와 자식이 같을 때 -> 부모 형질의 2진수와 같으면 부모 형질을 갖고 있는 것
SELECT D1.ID, D1.GENOTYPE, D2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA D1
JOIN ECOLI_DATA D2
ON D1.PARENT_ID = D2.ID
WHERE D2.GENOTYPE & D1.GENOTYPE = D2.GENOTYPE
ORDER BY D1.ID;