-- 부서ID, 영문부서명, 편균 연봉
-- 평균연봉 -> 소수점 첫째 자리에서 반올림: AVG_SAL
-- 부서별 평균 연봉 내림차순
SELECT E.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES E
JOIN HR_DEPARTMENT D
ON E.DEPT_ID = D.DEPT_ID
GROUP BY DEPT_ID
ORDER BY AVG_SAL DESC;