-- 코드를 입력하세요
SELECT '/home/grep/src/' || UGF.BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE UGF, USED_GOODS_BOARD UGB
WHERE 1 = 1
        AND UGF.BOARD_ID = UGB.BOARD_ID
        AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY UGF.FILE_ID DESC;